spring:
  profiles:
    active: local # 기본 환경 선택

# local 환경
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:testdb
    data: classpath:data-h2.sql # 시작할때 실행시킬 script
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false # Spring Boot 2.0 부터 기본값이 true로 바뀜. https://jojoldu.tistory.com/295 참고
    defer-datasource-initialization: true # Spring Boot 2.5 이상일 경우 사용. https://www.inflearn.com/questions/219978 참고
  h2:
    console:
      enabled: true